services:
  proxy-scraper-api:
    container_name: proxy-scraper-api
    image: proxy-scraper-api:latest
    networks:
      - proxy-scraper-api-network
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./out:/app/out
    environment:
      - TZ=UTC
    restart: unless-stopped

networks:
  proxy-scraper-api-network:
    driver: bridge
    name: proxy-scraper-api-network

volumes:
  out: